version: '3.8'

services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "user"
      MONGO_INITDB_ROOT_PASSWORD: "pass"

  writer1:
    image: ${DOCKER_REGISTRY-}writer
    container_name: writer1
    build:
      context: ./writer
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      BROKER_URL: "host.docker.internal:29092"

  writer2:
    image: ${DOCKER_REGISTRY-}writer
    container_name: writer2
    build:
      context: ./writer
      dockerfile: Dockerfile
    ports:
      - "8082:8081"
    environment:
      BROKER_URL: "host.docker.internal:29092"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - writer1
      - writer2

  reader:
    image: ${DOCKER_REGISTRY-}reader
    container_name: reader
    build:
      context: ./reader
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      BROKER_URL: "host.docker.internal:29092"
      DB_URI: "mongodb://user:pass@mongodb:27017"
    depends_on:
      - mongodb

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
