version: '3.8'

services:
  writer:
    image: ${DOCKER_REGISTRY-}writer
    container_name: writer
    build:
      context: ./writer
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      BROKER_URL: "host.docker.internal:29092"

  reader:
    image: ${DOCKER_REGISTRY-}reader
    container_name: reader
    build:
      context: ./reader
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      BROKER_URL: "host.docker.internal:29092"
